main: com.inaiga.rpgplugin.MainClass
name: RPGPlugin
version: 1.0
api-version: 1.14
author: INatsuz & Varsenaiga & TheFirePrince & GoddessAsuna & Robiborg
description: All in one RPG experience, with abilities, custom items and an inbuilt questing system.
commands:
  class:
    usage: /class <CharacterClass>
    description: Creates an RPG Character
    permission-message: You don't have the permission to do this command.
  checkchar:
    usage: /checkchar
    description: Checks the classes of your characters
    permission-message: You don't have the permission to do this command.
  choosechar:
    usage: /choosechar <index>
    description: Chooses a character and sets it to your active character
    permission-message: You don't have the permission to do this command.
  skillmenu:
    usage: /skillmenu
    description: Opens the Skill Tree Menu
    permission-message: You don't have the permission to do this command.
  delchar:
    usage: /delchar
    description: Deletes a RPG Character
    permission-message: You don't have the permission to do this command.
  customitems:
    usage: /customitems
    description: Gives the player all the custom items
    permission-message: You don't have the permission to do this command.
  custommob:
    usage: /custommob
    description: Spawns the current test custom mob
    permission-message: You don't have the permission to do this command.
  npc:
    usage: /npc
    description: Spawns an NPC
    permission-message: You don't have the permission to do this command.