main: com.inaiga.rpgplugin.MainClass
name: RPGPlugin
version: 1.0
author: Tiago & Vasco
description: RPG é fixe
commands:
  Group:
    usage: /<command> <Group> <TargetPlayer>
    description: Gives a certain Group Permission to the player
    permission-message: You don't have the permission to do this command.
